language: c

compiler:
  - clang
  - gcc

script:
  - clang --coverage ntpdatehttp.c -lcurl -o ntpdatehttp
  - gcov ntpdatehttp.c
  - gcc --coverage ntpdatehttp.c -lcurl -o ntpdatehttp
  - gcov ntpdatehttp.c
  
after_success:
    bash <(curl -s https://codecov.io/bash)
